//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Trabajo2024_03_19.WebReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CargaHorariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargaPeliculasOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargaDescripcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargaPaisesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargaCiudadesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AhorcadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Cuatro_ImagenesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargaVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agenda_LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agenda_CargaContactosOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agenda_DetalleContactoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agenda_AgregaContactoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agenda_EditaContactoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agenda_BorraContactoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agenda_CargaPaisesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Angel_loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Angel_AlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Angel_MensajesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Angel_CalificacionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Angel_EstadoCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Angel_TareasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfigIniOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://201.168.154.186/webservices/wspruebas/service1.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CargaHorariosCompletedEventHandler CargaHorariosCompleted;
        
        /// <remarks/>
        public event CargaPeliculasCompletedEventHandler CargaPeliculasCompleted;
        
        /// <remarks/>
        public event CargaDescripcionCompletedEventHandler CargaDescripcionCompleted;
        
        /// <remarks/>
        public event CargaPaisesCompletedEventHandler CargaPaisesCompleted;
        
        /// <remarks/>
        public event CargaCiudadesCompletedEventHandler CargaCiudadesCompleted;
        
        /// <remarks/>
        public event AhorcadoCompletedEventHandler AhorcadoCompleted;
        
        /// <remarks/>
        public event Cuatro_ImagenesCompletedEventHandler Cuatro_ImagenesCompleted;
        
        /// <remarks/>
        public event CargaVentasCompletedEventHandler CargaVentasCompleted;
        
        /// <remarks/>
        public event Agenda_LoginCompletedEventHandler Agenda_LoginCompleted;
        
        /// <remarks/>
        public event Agenda_CargaContactosCompletedEventHandler Agenda_CargaContactosCompleted;
        
        /// <remarks/>
        public event Agenda_DetalleContactoCompletedEventHandler Agenda_DetalleContactoCompleted;
        
        /// <remarks/>
        public event Agenda_AgregaContactoCompletedEventHandler Agenda_AgregaContactoCompleted;
        
        /// <remarks/>
        public event Agenda_EditaContactoCompletedEventHandler Agenda_EditaContactoCompleted;
        
        /// <remarks/>
        public event Agenda_BorraContactoCompletedEventHandler Agenda_BorraContactoCompleted;
        
        /// <remarks/>
        public event Agenda_CargaPaisesCompletedEventHandler Agenda_CargaPaisesCompleted;
        
        /// <remarks/>
        public event Angel_loginCompletedEventHandler Angel_loginCompleted;
        
        /// <remarks/>
        public event Angel_AlumnoCompletedEventHandler Angel_AlumnoCompleted;
        
        /// <remarks/>
        public event Angel_MensajesCompletedEventHandler Angel_MensajesCompleted;
        
        /// <remarks/>
        public event Angel_CalificacionesCompletedEventHandler Angel_CalificacionesCompleted;
        
        /// <remarks/>
        public event Angel_EstadoCuentaCompletedEventHandler Angel_EstadoCuentaCompleted;
        
        /// <remarks/>
        public event Angel_TareasCompletedEventHandler Angel_TareasCompleted;
        
        /// <remarks/>
        public event ConfigIniCompletedEventHandler ConfigIniCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargaHorarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CargaHorarios(int pelicula) {
            object[] results = this.Invoke("CargaHorarios", new object[] {
                        pelicula});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CargaHorariosAsync(int pelicula) {
            this.CargaHorariosAsync(pelicula, null);
        }
        
        /// <remarks/>
        public void CargaHorariosAsync(int pelicula, object userState) {
            if ((this.CargaHorariosOperationCompleted == null)) {
                this.CargaHorariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaHorariosOperationCompleted);
            }
            this.InvokeAsync("CargaHorarios", new object[] {
                        pelicula}, this.CargaHorariosOperationCompleted, userState);
        }
        
        private void OnCargaHorariosOperationCompleted(object arg) {
            if ((this.CargaHorariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaHorariosCompleted(this, new CargaHorariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargaPeliculas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CargaPeliculas() {
            object[] results = this.Invoke("CargaPeliculas", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CargaPeliculasAsync() {
            this.CargaPeliculasAsync(null);
        }
        
        /// <remarks/>
        public void CargaPeliculasAsync(object userState) {
            if ((this.CargaPeliculasOperationCompleted == null)) {
                this.CargaPeliculasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaPeliculasOperationCompleted);
            }
            this.InvokeAsync("CargaPeliculas", new object[0], this.CargaPeliculasOperationCompleted, userState);
        }
        
        private void OnCargaPeliculasOperationCompleted(object arg) {
            if ((this.CargaPeliculasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaPeliculasCompleted(this, new CargaPeliculasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargaDescripcion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CargaDescripcion(int pelicula) {
            object[] results = this.Invoke("CargaDescripcion", new object[] {
                        pelicula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CargaDescripcionAsync(int pelicula) {
            this.CargaDescripcionAsync(pelicula, null);
        }
        
        /// <remarks/>
        public void CargaDescripcionAsync(int pelicula, object userState) {
            if ((this.CargaDescripcionOperationCompleted == null)) {
                this.CargaDescripcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaDescripcionOperationCompleted);
            }
            this.InvokeAsync("CargaDescripcion", new object[] {
                        pelicula}, this.CargaDescripcionOperationCompleted, userState);
        }
        
        private void OnCargaDescripcionOperationCompleted(object arg) {
            if ((this.CargaDescripcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaDescripcionCompleted(this, new CargaDescripcionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargaPaises", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CargaPaises() {
            object[] results = this.Invoke("CargaPaises", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CargaPaisesAsync() {
            this.CargaPaisesAsync(null);
        }
        
        /// <remarks/>
        public void CargaPaisesAsync(object userState) {
            if ((this.CargaPaisesOperationCompleted == null)) {
                this.CargaPaisesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaPaisesOperationCompleted);
            }
            this.InvokeAsync("CargaPaises", new object[0], this.CargaPaisesOperationCompleted, userState);
        }
        
        private void OnCargaPaisesOperationCompleted(object arg) {
            if ((this.CargaPaisesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaPaisesCompleted(this, new CargaPaisesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargaCiudades", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CargaCiudades(int Paises) {
            object[] results = this.Invoke("CargaCiudades", new object[] {
                        Paises});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CargaCiudadesAsync(int Paises) {
            this.CargaCiudadesAsync(Paises, null);
        }
        
        /// <remarks/>
        public void CargaCiudadesAsync(int Paises, object userState) {
            if ((this.CargaCiudadesOperationCompleted == null)) {
                this.CargaCiudadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaCiudadesOperationCompleted);
            }
            this.InvokeAsync("CargaCiudades", new object[] {
                        Paises}, this.CargaCiudadesOperationCompleted, userState);
        }
        
        private void OnCargaCiudadesOperationCompleted(object arg) {
            if ((this.CargaCiudadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaCiudadesCompleted(this, new CargaCiudadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ahorcado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Ahorcado() {
            object[] results = this.Invoke("Ahorcado", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AhorcadoAsync() {
            this.AhorcadoAsync(null);
        }
        
        /// <remarks/>
        public void AhorcadoAsync(object userState) {
            if ((this.AhorcadoOperationCompleted == null)) {
                this.AhorcadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAhorcadoOperationCompleted);
            }
            this.InvokeAsync("Ahorcado", new object[0], this.AhorcadoOperationCompleted, userState);
        }
        
        private void OnAhorcadoOperationCompleted(object arg) {
            if ((this.AhorcadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AhorcadoCompleted(this, new AhorcadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Cuatro_Imagenes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Cuatro_Imagenes() {
            object[] results = this.Invoke("Cuatro_Imagenes", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Cuatro_ImagenesAsync() {
            this.Cuatro_ImagenesAsync(null);
        }
        
        /// <remarks/>
        public void Cuatro_ImagenesAsync(object userState) {
            if ((this.Cuatro_ImagenesOperationCompleted == null)) {
                this.Cuatro_ImagenesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCuatro_ImagenesOperationCompleted);
            }
            this.InvokeAsync("Cuatro_Imagenes", new object[0], this.Cuatro_ImagenesOperationCompleted, userState);
        }
        
        private void OnCuatro_ImagenesOperationCompleted(object arg) {
            if ((this.Cuatro_ImagenesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Cuatro_ImagenesCompleted(this, new Cuatro_ImagenesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargaVentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CargaVentas() {
            object[] results = this.Invoke("CargaVentas", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CargaVentasAsync() {
            this.CargaVentasAsync(null);
        }
        
        /// <remarks/>
        public void CargaVentasAsync(object userState) {
            if ((this.CargaVentasOperationCompleted == null)) {
                this.CargaVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaVentasOperationCompleted);
            }
            this.InvokeAsync("CargaVentas", new object[0], this.CargaVentasOperationCompleted, userState);
        }
        
        private void OnCargaVentasOperationCompleted(object arg) {
            if ((this.CargaVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaVentasCompleted(this, new CargaVentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agenda_Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Agenda_Login(string usu, string pass) {
            object[] results = this.Invoke("Agenda_Login", new object[] {
                        usu,
                        pass});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Agenda_LoginAsync(string usu, string pass) {
            this.Agenda_LoginAsync(usu, pass, null);
        }
        
        /// <remarks/>
        public void Agenda_LoginAsync(string usu, string pass, object userState) {
            if ((this.Agenda_LoginOperationCompleted == null)) {
                this.Agenda_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgenda_LoginOperationCompleted);
            }
            this.InvokeAsync("Agenda_Login", new object[] {
                        usu,
                        pass}, this.Agenda_LoginOperationCompleted, userState);
        }
        
        private void OnAgenda_LoginOperationCompleted(object arg) {
            if ((this.Agenda_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agenda_LoginCompleted(this, new Agenda_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agenda_CargaContactos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Agenda_CargaContactos() {
            object[] results = this.Invoke("Agenda_CargaContactos", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Agenda_CargaContactosAsync() {
            this.Agenda_CargaContactosAsync(null);
        }
        
        /// <remarks/>
        public void Agenda_CargaContactosAsync(object userState) {
            if ((this.Agenda_CargaContactosOperationCompleted == null)) {
                this.Agenda_CargaContactosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgenda_CargaContactosOperationCompleted);
            }
            this.InvokeAsync("Agenda_CargaContactos", new object[0], this.Agenda_CargaContactosOperationCompleted, userState);
        }
        
        private void OnAgenda_CargaContactosOperationCompleted(object arg) {
            if ((this.Agenda_CargaContactosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agenda_CargaContactosCompleted(this, new Agenda_CargaContactosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agenda_DetalleContacto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Agenda_DetalleContacto(int id) {
            object[] results = this.Invoke("Agenda_DetalleContacto", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Agenda_DetalleContactoAsync(int id) {
            this.Agenda_DetalleContactoAsync(id, null);
        }
        
        /// <remarks/>
        public void Agenda_DetalleContactoAsync(int id, object userState) {
            if ((this.Agenda_DetalleContactoOperationCompleted == null)) {
                this.Agenda_DetalleContactoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgenda_DetalleContactoOperationCompleted);
            }
            this.InvokeAsync("Agenda_DetalleContacto", new object[] {
                        id}, this.Agenda_DetalleContactoOperationCompleted, userState);
        }
        
        private void OnAgenda_DetalleContactoOperationCompleted(object arg) {
            if ((this.Agenda_DetalleContactoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agenda_DetalleContactoCompleted(this, new Agenda_DetalleContactoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agenda_AgregaContacto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Agenda_AgregaContacto(string nom, string tel, string email, int edad, int nacio) {
            object[] results = this.Invoke("Agenda_AgregaContacto", new object[] {
                        nom,
                        tel,
                        email,
                        edad,
                        nacio});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Agenda_AgregaContactoAsync(string nom, string tel, string email, int edad, int nacio) {
            this.Agenda_AgregaContactoAsync(nom, tel, email, edad, nacio, null);
        }
        
        /// <remarks/>
        public void Agenda_AgregaContactoAsync(string nom, string tel, string email, int edad, int nacio, object userState) {
            if ((this.Agenda_AgregaContactoOperationCompleted == null)) {
                this.Agenda_AgregaContactoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgenda_AgregaContactoOperationCompleted);
            }
            this.InvokeAsync("Agenda_AgregaContacto", new object[] {
                        nom,
                        tel,
                        email,
                        edad,
                        nacio}, this.Agenda_AgregaContactoOperationCompleted, userState);
        }
        
        private void OnAgenda_AgregaContactoOperationCompleted(object arg) {
            if ((this.Agenda_AgregaContactoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agenda_AgregaContactoCompleted(this, new Agenda_AgregaContactoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agenda_EditaContacto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Agenda_EditaContacto(int id, string nom, string tel, string email, int edad, int nacio) {
            object[] results = this.Invoke("Agenda_EditaContacto", new object[] {
                        id,
                        nom,
                        tel,
                        email,
                        edad,
                        nacio});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Agenda_EditaContactoAsync(int id, string nom, string tel, string email, int edad, int nacio) {
            this.Agenda_EditaContactoAsync(id, nom, tel, email, edad, nacio, null);
        }
        
        /// <remarks/>
        public void Agenda_EditaContactoAsync(int id, string nom, string tel, string email, int edad, int nacio, object userState) {
            if ((this.Agenda_EditaContactoOperationCompleted == null)) {
                this.Agenda_EditaContactoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgenda_EditaContactoOperationCompleted);
            }
            this.InvokeAsync("Agenda_EditaContacto", new object[] {
                        id,
                        nom,
                        tel,
                        email,
                        edad,
                        nacio}, this.Agenda_EditaContactoOperationCompleted, userState);
        }
        
        private void OnAgenda_EditaContactoOperationCompleted(object arg) {
            if ((this.Agenda_EditaContactoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agenda_EditaContactoCompleted(this, new Agenda_EditaContactoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agenda_BorraContacto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Agenda_BorraContacto(int id) {
            object[] results = this.Invoke("Agenda_BorraContacto", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Agenda_BorraContactoAsync(int id) {
            this.Agenda_BorraContactoAsync(id, null);
        }
        
        /// <remarks/>
        public void Agenda_BorraContactoAsync(int id, object userState) {
            if ((this.Agenda_BorraContactoOperationCompleted == null)) {
                this.Agenda_BorraContactoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgenda_BorraContactoOperationCompleted);
            }
            this.InvokeAsync("Agenda_BorraContacto", new object[] {
                        id}, this.Agenda_BorraContactoOperationCompleted, userState);
        }
        
        private void OnAgenda_BorraContactoOperationCompleted(object arg) {
            if ((this.Agenda_BorraContactoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agenda_BorraContactoCompleted(this, new Agenda_BorraContactoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agenda_CargaPaises", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Agenda_CargaPaises() {
            object[] results = this.Invoke("Agenda_CargaPaises", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Agenda_CargaPaisesAsync() {
            this.Agenda_CargaPaisesAsync(null);
        }
        
        /// <remarks/>
        public void Agenda_CargaPaisesAsync(object userState) {
            if ((this.Agenda_CargaPaisesOperationCompleted == null)) {
                this.Agenda_CargaPaisesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgenda_CargaPaisesOperationCompleted);
            }
            this.InvokeAsync("Agenda_CargaPaises", new object[0], this.Agenda_CargaPaisesOperationCompleted, userState);
        }
        
        private void OnAgenda_CargaPaisesOperationCompleted(object arg) {
            if ((this.Agenda_CargaPaisesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agenda_CargaPaisesCompleted(this, new Agenda_CargaPaisesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Angel_login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Angel_login(string matricula, string clave) {
            object[] results = this.Invoke("Angel_login", new object[] {
                        matricula,
                        clave});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Angel_loginAsync(string matricula, string clave) {
            this.Angel_loginAsync(matricula, clave, null);
        }
        
        /// <remarks/>
        public void Angel_loginAsync(string matricula, string clave, object userState) {
            if ((this.Angel_loginOperationCompleted == null)) {
                this.Angel_loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAngel_loginOperationCompleted);
            }
            this.InvokeAsync("Angel_login", new object[] {
                        matricula,
                        clave}, this.Angel_loginOperationCompleted, userState);
        }
        
        private void OnAngel_loginOperationCompleted(object arg) {
            if ((this.Angel_loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Angel_loginCompleted(this, new Angel_loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Angel_Alumno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Angel_Alumno(string matricula) {
            object[] results = this.Invoke("Angel_Alumno", new object[] {
                        matricula});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Angel_AlumnoAsync(string matricula) {
            this.Angel_AlumnoAsync(matricula, null);
        }
        
        /// <remarks/>
        public void Angel_AlumnoAsync(string matricula, object userState) {
            if ((this.Angel_AlumnoOperationCompleted == null)) {
                this.Angel_AlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAngel_AlumnoOperationCompleted);
            }
            this.InvokeAsync("Angel_Alumno", new object[] {
                        matricula}, this.Angel_AlumnoOperationCompleted, userState);
        }
        
        private void OnAngel_AlumnoOperationCompleted(object arg) {
            if ((this.Angel_AlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Angel_AlumnoCompleted(this, new Angel_AlumnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Angel_Mensajes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Angel_Mensajes(string matricula, string grupo, string periodo) {
            object[] results = this.Invoke("Angel_Mensajes", new object[] {
                        matricula,
                        grupo,
                        periodo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Angel_MensajesAsync(string matricula, string grupo, string periodo) {
            this.Angel_MensajesAsync(matricula, grupo, periodo, null);
        }
        
        /// <remarks/>
        public void Angel_MensajesAsync(string matricula, string grupo, string periodo, object userState) {
            if ((this.Angel_MensajesOperationCompleted == null)) {
                this.Angel_MensajesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAngel_MensajesOperationCompleted);
            }
            this.InvokeAsync("Angel_Mensajes", new object[] {
                        matricula,
                        grupo,
                        periodo}, this.Angel_MensajesOperationCompleted, userState);
        }
        
        private void OnAngel_MensajesOperationCompleted(object arg) {
            if ((this.Angel_MensajesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Angel_MensajesCompleted(this, new Angel_MensajesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Angel_Calificaciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Angel_Calificaciones(string matricula, string periodo) {
            object[] results = this.Invoke("Angel_Calificaciones", new object[] {
                        matricula,
                        periodo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Angel_CalificacionesAsync(string matricula, string periodo) {
            this.Angel_CalificacionesAsync(matricula, periodo, null);
        }
        
        /// <remarks/>
        public void Angel_CalificacionesAsync(string matricula, string periodo, object userState) {
            if ((this.Angel_CalificacionesOperationCompleted == null)) {
                this.Angel_CalificacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAngel_CalificacionesOperationCompleted);
            }
            this.InvokeAsync("Angel_Calificaciones", new object[] {
                        matricula,
                        periodo}, this.Angel_CalificacionesOperationCompleted, userState);
        }
        
        private void OnAngel_CalificacionesOperationCompleted(object arg) {
            if ((this.Angel_CalificacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Angel_CalificacionesCompleted(this, new Angel_CalificacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Angel_EstadoCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Angel_EstadoCuenta(string matricula, string periodo) {
            object[] results = this.Invoke("Angel_EstadoCuenta", new object[] {
                        matricula,
                        periodo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Angel_EstadoCuentaAsync(string matricula, string periodo) {
            this.Angel_EstadoCuentaAsync(matricula, periodo, null);
        }
        
        /// <remarks/>
        public void Angel_EstadoCuentaAsync(string matricula, string periodo, object userState) {
            if ((this.Angel_EstadoCuentaOperationCompleted == null)) {
                this.Angel_EstadoCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAngel_EstadoCuentaOperationCompleted);
            }
            this.InvokeAsync("Angel_EstadoCuenta", new object[] {
                        matricula,
                        periodo}, this.Angel_EstadoCuentaOperationCompleted, userState);
        }
        
        private void OnAngel_EstadoCuentaOperationCompleted(object arg) {
            if ((this.Angel_EstadoCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Angel_EstadoCuentaCompleted(this, new Angel_EstadoCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Angel_Tareas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Angel_Tareas(string grupo, string periodo) {
            object[] results = this.Invoke("Angel_Tareas", new object[] {
                        grupo,
                        periodo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Angel_TareasAsync(string grupo, string periodo) {
            this.Angel_TareasAsync(grupo, periodo, null);
        }
        
        /// <remarks/>
        public void Angel_TareasAsync(string grupo, string periodo, object userState) {
            if ((this.Angel_TareasOperationCompleted == null)) {
                this.Angel_TareasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAngel_TareasOperationCompleted);
            }
            this.InvokeAsync("Angel_Tareas", new object[] {
                        grupo,
                        periodo}, this.Angel_TareasOperationCompleted, userState);
        }
        
        private void OnAngel_TareasOperationCompleted(object arg) {
            if ((this.Angel_TareasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Angel_TareasCompleted(this, new Angel_TareasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfigIni", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfigIni(string Hash) {
            object[] results = this.Invoke("ConfigIni", new object[] {
                        Hash});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfigIniAsync(string Hash) {
            this.ConfigIniAsync(Hash, null);
        }
        
        /// <remarks/>
        public void ConfigIniAsync(string Hash, object userState) {
            if ((this.ConfigIniOperationCompleted == null)) {
                this.ConfigIniOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfigIniOperationCompleted);
            }
            this.InvokeAsync("ConfigIni", new object[] {
                        Hash}, this.ConfigIniOperationCompleted, userState);
        }
        
        private void OnConfigIniOperationCompleted(object arg) {
            if ((this.ConfigIniCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfigIniCompleted(this, new ConfigIniCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CargaHorariosCompletedEventHandler(object sender, CargaHorariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaHorariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaHorariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CargaPeliculasCompletedEventHandler(object sender, CargaPeliculasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaPeliculasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaPeliculasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CargaDescripcionCompletedEventHandler(object sender, CargaDescripcionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaDescripcionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaDescripcionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CargaPaisesCompletedEventHandler(object sender, CargaPaisesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaPaisesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaPaisesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CargaCiudadesCompletedEventHandler(object sender, CargaCiudadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaCiudadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaCiudadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AhorcadoCompletedEventHandler(object sender, AhorcadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AhorcadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AhorcadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Cuatro_ImagenesCompletedEventHandler(object sender, Cuatro_ImagenesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Cuatro_ImagenesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Cuatro_ImagenesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CargaVentasCompletedEventHandler(object sender, CargaVentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaVentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaVentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Agenda_LoginCompletedEventHandler(object sender, Agenda_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agenda_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agenda_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Agenda_CargaContactosCompletedEventHandler(object sender, Agenda_CargaContactosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agenda_CargaContactosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agenda_CargaContactosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Agenda_DetalleContactoCompletedEventHandler(object sender, Agenda_DetalleContactoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agenda_DetalleContactoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agenda_DetalleContactoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Agenda_AgregaContactoCompletedEventHandler(object sender, Agenda_AgregaContactoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agenda_AgregaContactoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agenda_AgregaContactoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Agenda_EditaContactoCompletedEventHandler(object sender, Agenda_EditaContactoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agenda_EditaContactoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agenda_EditaContactoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Agenda_BorraContactoCompletedEventHandler(object sender, Agenda_BorraContactoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agenda_BorraContactoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agenda_BorraContactoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Agenda_CargaPaisesCompletedEventHandler(object sender, Agenda_CargaPaisesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agenda_CargaPaisesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agenda_CargaPaisesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Angel_loginCompletedEventHandler(object sender, Angel_loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Angel_loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Angel_loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Angel_AlumnoCompletedEventHandler(object sender, Angel_AlumnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Angel_AlumnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Angel_AlumnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Angel_MensajesCompletedEventHandler(object sender, Angel_MensajesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Angel_MensajesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Angel_MensajesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Angel_CalificacionesCompletedEventHandler(object sender, Angel_CalificacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Angel_CalificacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Angel_CalificacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Angel_EstadoCuentaCompletedEventHandler(object sender, Angel_EstadoCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Angel_EstadoCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Angel_EstadoCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Angel_TareasCompletedEventHandler(object sender, Angel_TareasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Angel_TareasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Angel_TareasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ConfigIniCompletedEventHandler(object sender, ConfigIniCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfigIniCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfigIniCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591